function [Ntrial Nsub] = BarsAndErrorPlotModel(DataMatrix,ModelMatrix1,Colors,Yinf,Ysup,Font,Frame);


[Ntrial Nsub]=size(DataMatrix);

curve= nanmean(DataMatrix,2);
sem  = std(DataMatrix')'/sqrt(Nsub);

model1= nanmean(ModelMatrix1,2);
semm1  = std(ModelMatrix1')'/sqrt(Nsub);


absci=1:Ntrial;

for n=1:Ntrial;
% first bar
bar(n,curve(n),...
    'FaceColor',Colors(n,:),...
    'EdgeColor',Colors(n,:),...
    'BarWidth',0.75,...
    'LineWidth',3);
hold on
errorbar(n,[curve(n)],[sem(n)],...
    'Color',[0 0 0],...
    'LineStyle','none',...
    'LineWidth',1);
end


% plot best model

errorbar(absci-Frame,model1,semm1,...
    'Color',[0 0 0],...
    'LineWidth',1,...
    'LineStyle','none',...
    'Marker','o',...
    'MarkerFaceColor',[1 1 1],...
    'MarkerSize',10);
hold on


ylim([Yinf Ysup]);
set(gca,'FontSize',Font,...
    'XLim',[0 Ntrial+1],...
    'XTick',[1:Ntrial],....
    'XTickLabel','');
